//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG_Projects_APP_Frontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFG_Projects_APP_Frontend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dependency.
        /// </summary>
        public static string AddDependencyLabel {
            get {
                return ResourceManager.GetString("AddDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add permissions:.
        /// </summary>
        public static string AddPermissionsLabel {
            get {
                return ResourceManager.GetString("AddPermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API found.
        /// </summary>
        public static string APIFoundMessage {
            get {
                return ResourceManager.GetString("APIFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API not found.
        /// </summary>
        public static string APINotFoundMessage {
            get {
                return ResourceManager.GetString("APINotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API not found, please test the connection first.
        /// </summary>
        public static string APINotFoundTestConnectionMessage {
            get {
                return ResourceManager.GetString("APINotFoundTestConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL updated successfully.
        /// </summary>
        public static string APIUpdatedMessage {
            get {
                return ResourceManager.GetString("APIUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid route and port.
        /// </summary>
        public static string APIValidationMessage {
            get {
                return ResourceManager.GetString("APIValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettingsNavigationTitle {
            get {
                return ResourceManager.GetString("AppSettingsNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to:.
        /// </summary>
        public static string AssignedToLabel {
            get {
                return ResourceManager.GetString("AssignedToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes, are you sure you want to edit another item?.
        /// </summary>
        public static string ChangeEditMessage {
            get {
                return ResourceManager.GetString("ChangeEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Edit.
        /// </summary>
        public static string ChangeEditMessageTitle {
            get {
                return ResourceManager.GetString("ChangeEditMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string ChangeEmailLabel {
            get {
                return ResourceManager.GetString("ChangeEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Username.
        /// </summary>
        public static string ChangeUsernameLabel {
            get {
                return ResourceManager.GetString("ChangeUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string ConfirmDeleteMessageTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user from the project?.
        /// </summary>
        public static string ConfirmRemoveUserMessage {
            get {
                return ResourceManager.GetString("ConfirmRemoveUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Removing User.
        /// </summary>
        public static string ConfirmRemoveUserTitle {
            get {
                return ResourceManager.GetString("ConfirmRemoveUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please test the connection first.
        /// </summary>
        public static string ConnectionTestMessage {
            get {
                return ResourceManager.GetString("ConnectionTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:.
        /// </summary>
        public static string ContentLabel {
            get {
                return ResourceManager.GetString("ContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect.
        /// </summary>
        public static string CouldNotConnectMessage {
            get {
                return ResourceManager.GetString("CouldNotConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Concept Board.
        /// </summary>
        public static string CreateBoardTitle {
            get {
                return ResourceManager.GetString("CreateBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Component.
        /// </summary>
        public static string CreateComponentTitle {
            get {
                return ResourceManager.GetString("CreateComponentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Concept.
        /// </summary>
        public static string CreateConceptButton {
            get {
                return ResourceManager.GetString("CreateConceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Concept.
        /// </summary>
        public static string CreateConceptTitle {
            get {
                return ResourceManager.GetString("CreateConceptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Container.
        /// </summary>
        public static string CreateContainerTitle {
            get {
                return ResourceManager.GetString("CreateContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Note.
        /// </summary>
        public static string CreateNoteTitle {
            get {
                return ResourceManager.GetString("CreateNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Progress Section.
        /// </summary>
        public static string CreateProgressSectionButton {
            get {
                return ResourceManager.GetString("CreateProgressSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Progress Section.
        /// </summary>
        public static string CreateProgressSectionTitle {
            get {
                return ResourceManager.GetString("CreateProgressSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProjectButton {
            get {
                return ResourceManager.GetString("CreateProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProjectTitle {
            get {
                return ResourceManager.GetString("CreateProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table.
        /// </summary>
        public static string CreateTableTitle {
            get {
                return ResourceManager.GetString("CreateTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task Board.
        /// </summary>
        public static string CreateTaskBoardButton {
            get {
                return ResourceManager.GetString("CreateTaskBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task Board.
        /// </summary>
        public static string CreateTaskBoardTitle {
            get {
                return ResourceManager.GetString("CreateTaskBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Progress Section.
        /// </summary>
        public static string CreateTaskProgressButton {
            get {
                return ResourceManager.GetString("CreateTaskProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task Section.
        /// </summary>
        public static string CreateTaskSectionButton {
            get {
                return ResourceManager.GetString("CreateTaskSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task Section.
        /// </summary>
        public static string CreateTaskSectionTitle {
            get {
                return ResourceManager.GetString("CreateTaskSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string CreateTaskTitle {
            get {
                return ResourceManager.GetString("CreateTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string DefaultColumnTitle {
            get {
                return ResourceManager.GetString("DefaultColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Board.
        /// </summary>
        public static string DefaultConceptBoardName {
            get {
                return ResourceManager.GetString("DefaultConceptBoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the default progress section.
        /// </summary>
        public static string DefaultProgressSectionDeletionMessage {
            get {
                return ResourceManager.GetString("DefaultProgressSectionDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Section.
        /// </summary>
        public static string DefaultProgressTitle {
            get {
                return ResourceManager.GetString("DefaultProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string DefaultSectionTitle {
            get {
                return ResourceManager.GetString("DefaultSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string DeletionConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletionConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Component.
        /// </summary>
        public static string EditComponentLabel {
            get {
                return ResourceManager.GetString("EditComponentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Concept.
        /// </summary>
        public static string EditConceptLabel {
            get {
                return ResourceManager.GetString("EditConceptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Progress Section.
        /// </summary>
        public static string EditProgressSectionLabel {
            get {
                return ResourceManager.GetString("EditProgressSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string EditProjectLabel {
            get {
                return ResourceManager.GetString("EditProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit TaskBoard.
        /// </summary>
        public static string EditTaskBoardLabel {
            get {
                return ResourceManager.GetString("EditTaskBoardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string EditTaskLabel {
            get {
                return ResourceManager.GetString("EditTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task Section.
        /// </summary>
        public static string EditTaskSectionLabel {
            get {
                return ResourceManager.GetString("EditTaskSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUserLabel {
            get {
                return ResourceManager.GetString("EditUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input an email.
        /// </summary>
        public static string EmailInputMessage {
            get {
                return ResourceManager.GetString("EmailInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to input an email.
        /// </summary>
        public static string EmailNotIntroducedMessage {
            get {
                return ResourceManager.GetString("EmailNotIntroducedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update the email.
        /// </summary>
        public static string EmailNotUpdatedMessage {
            get {
                return ResourceManager.GetString("EmailNotUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully updated.
        /// </summary>
        public static string EmailUpdatedMessage {
            get {
                return ResourceManager.GetString("EmailUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all data.
        /// </summary>
        public static string EnterAllDataMessage {
            get {
                return ResourceManager.GetString("EnterAllDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeNavigationTitle {
            get {
                return ResourceManager.GetString("HomeNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Date:.
        /// </summary>
        public static string LimitDateLabel {
            get {
                return ResourceManager.GetString("LimitDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string LoginPageMessage {
            get {
                return ResourceManager.GetString("LoginPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOutNavigationTitle {
            get {
                return ResourceManager.GetString("LogOutNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies Progress Value:.
        /// </summary>
        public static string ModifiesValueLabel {
            get {
                return ResourceManager.GetString("ModifiesValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameIsRequiredMessage {
            get {
                return ResourceManager.GetString("NameIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email:.
        /// </summary>
        public static string NewEmailLabel {
            get {
                return ResourceManager.GetString("NewEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username.
        /// </summary>
        public static string NewUsernameLabel {
            get {
                return ResourceManager.GetString("NewUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to do that.
        /// </summary>
        public static string NoPermissionMessage {
            get {
                return ResourceManager.GetString("NoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to input a password and confirm it.
        /// </summary>
        public static string PasswordNotIntroducedMessage {
            get {
                return ResourceManager.GetString("PasswordNotIntroducedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update the password.
        /// </summary>
        public static string PasswordNotUpdatedMessage {
            get {
                return ResourceManager.GetString("PasswordNotUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must match.
        /// </summary>
        public static string PasswordsMustMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsMustMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated.
        /// </summary>
        public static string PasswordUpdatedMessage {
            get {
                return ResourceManager.GetString("PasswordUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityLabel {
            get {
                return ResourceManager.GetString("PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress value must be between 0 and 100.
        /// </summary>
        public static string ProgressValidationMessage {
            get {
                return ResourceManager.GetString("ProgressValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Dependency.
        /// </summary>
        public static string RemoveDependencyButton {
            get {
                return ResourceManager.GetString("RemoveDependencyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove permissions:.
        /// </summary>
        public static string RemovePermissionsLabel {
            get {
                return ResourceManager.GetString("RemovePermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the app to apply the changes.
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save API location.
        /// </summary>
        public static string SaveApiLocationButton {
            get {
                return ResourceManager.GetString("SaveApiLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveDependencyChangesButton {
            get {
                return ResourceManager.GetString("SaveDependencyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user by email.
        /// </summary>
        public static string SearchUserByEmailLabel {
            get {
                return ResourceManager.GetString("SearchUserByEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role.
        /// </summary>
        public static string SelectRoleLabel {
            get {
                return ResourceManager.GetString("SelectRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string ServerIPLabel {
            get {
                return ResourceManager.GetString("ServerIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessMessageTitle {
            get {
                return ResourceManager.GetString("SuccessMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task is already a dependency.
        /// </summary>
        public static string TaskAlreadyADependencyMessage {
            get {
                return ResourceManager.GetString("TaskAlreadyADependencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a task.
        /// </summary>
        public static string TaskNotSelectedMessage {
            get {
                return ResourceManager.GetString("TaskNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnectionButton {
            get {
                return ResourceManager.GetString("TestConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings.
        /// </summary>
        public static string TitleAppSettingsPage {
            get {
                return ResourceManager.GetString("TitleAppSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string TitleIsRequiredMessage {
            get {
                return ResourceManager.GetString("TitleIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock at:.
        /// </summary>
        public static string UnlockAtLabel {
            get {
                return ResourceManager.GetString("UnlockAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added to project.
        /// </summary>
        public static string UserAddedToProjectMessage {
            get {
                return ResourceManager.GetString("UserAddedToProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists in the project.
        /// </summary>
        public static string UserAlreadyInProjectMessage {
            get {
                return ResourceManager.GetString("UserAlreadyInProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to input a username.
        /// </summary>
        public static string UsernameNotIntroducedMessage {
            get {
                return ResourceManager.GetString("UsernameNotIntroducedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update the username.
        /// </summary>
        public static string UsernameNotUpdatedMessage {
            get {
                return ResourceManager.GetString("UsernameNotUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username successfully updated.
        /// </summary>
        public static string UsernameUpdatedMessage {
            get {
                return ResourceManager.GetString("UsernameUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to confirm your identity to modify your user settings.
        /// </summary>
        public static string UserSettingsMessage {
            get {
                return ResourceManager.GetString("UserSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string UserSettingsMessageTitle {
            get {
                return ResourceManager.GetString("UserSettingsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettingsNavigationTitle {
            get {
                return ResourceManager.GetString("UserSettingsNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
